import { SavedEvent, SavedTimetable } from "@/lib/schemas";

export const DEMO_EVENTS: SavedEvent[] = [
  {
    id: "demo-1",
    courseCode: "CSE 309",
    courseName: "Advanced Java Programming",
    room: "C 509",
    dayOfWeek: "Monday",
    startTime: "11:00",
    endTime: "12:50",
    faculty: "Ms. Gudapati Maneesha",
    reminderEnabled: true,
  },
  {
    id: "demo-2",
    courseCode: "CSE 309",
    courseName: "Advanced Java Programming",
    room: "C 509",
    dayOfWeek: "Wednesday",
    startTime: "11:00",
    endTime: "12:50",
    faculty: "Ms. Gudapati Maneesha",
    reminderEnabled: true,
  },
  {
    id: "demo-3",
    courseCode: "MAT 201",
    courseName: "Mathematics",
    room: "C 302",
    dayOfWeek: "Tuesday",
    startTime: "09:00",
    endTime: "09:50",
    faculty: "Dr. Rajesh Kumar",
    reminderEnabled: true,
  },
  {
    id: "demo-4",
    courseCode: "MAT 201",
    courseName: "Mathematics",
    room: "C 302",
    dayOfWeek: "Thursday",
    startTime: "09:00",
    endTime: "09:50",
    faculty: "Dr. Rajesh Kumar",
    reminderEnabled: true,
  },
  {
    id: "demo-5",
    courseCode: "CSE 211",
    courseName: "Programming Lab",
    room: "Lab 3",
    dayOfWeek: "Wednesday",
    startTime: "14:00",
    endTime: "16:50",
    faculty: "Prof. Anita Sharma",
    reminderEnabled: true,
  },
  {
    id: "demo-6",
    courseCode: "CSE 205",
    courseName: "Data Structures",
    room: "C 401",
    dayOfWeek: "Monday",
    startTime: "09:00",
    endTime: "09:50",
    faculty: "Dr. Priya Nair",
    reminderEnabled: true,
  },
  {
    id: "demo-7",
    courseCode: "CSE 205",
    courseName: "Data Structures",
    room: "C 401",
    dayOfWeek: "Thursday",
    startTime: "11:00",
    endTime: "11:50",
    faculty: "Dr. Priya Nair",
    reminderEnabled: true,
  },
  {
    id: "demo-8",
    courseCode: "CSE 207",
    courseName: "Computer Networks",
    room: "C 305",
    dayOfWeek: "Tuesday",
    startTime: "11:00",
    endTime: "12:50",
    faculty: "Dr. Vikram Singh",
    reminderEnabled: true,
  },
  {
    id: "demo-9",
    courseCode: "CSE 207",
    courseName: "Computer Networks",
    room: "C 305",
    dayOfWeek: "Friday",
    startTime: "09:00",
    endTime: "09:50",
    faculty: "Dr. Vikram Singh",
    reminderEnabled: true,
  },
  {
    id: "demo-10",
    courseCode: "CSE 203",
    courseName: "Python Programming",
    room: "C 210",
    dayOfWeek: "Friday",
    startTime: "13:00",
    endTime: "14:50",
    faculty: "Ms. Kavitha Reddy",
    reminderEnabled: true,
  },
  {
    id: "demo-11",
    courseCode: "CSE 203",
    courseName: "Python Programming",
    room: "C 210",
    dayOfWeek: "Wednesday",
    startTime: "09:00",
    endTime: "09:50",
    faculty: "Ms. Kavitha Reddy",
    reminderEnabled: true,
  },
  {
    id: "demo-12",
    courseCode: "HUM 101",
    courseName: "Professional Ethics",
    room: "C 102",
    dayOfWeek: "Thursday",
    startTime: "14:00",
    endTime: "14:50",
    faculty: "Dr. Meena Iyer",
    reminderEnabled: true,
  },
];

export function createDemoTimetable(): SavedTimetable {
  const now = new Date().toISOString();
  return {
    id: "demo-timetable",
    name: "My Timetable",
    semesterStart: "2026-09-28",
    semesterEnd: "2026-12-15",
    timezone: "Asia/Kolkata",
    events: DEMO_EVENTS,
    createdAt: now,
    updatedAt: now,
  };
}
